Repository duumbling/e-commerce-application, pull requests merged in 2023-09, with the labels that each got.

#156 Products search
  package-lock.json
  package.json
  src/app/store.ts
  src/entities/products-search/api/search.ts
  src/entities/products-search/index.ts
  src/entities/products-search/model/hooks.ts
  src/entities/products-search/model/slice.ts
  src/entities/products-search/ui/ProductsSearch.tsx
  src/features/ProductCardsView/api/products.ts
  src/features/ProductCardsView/lib/helpers.ts
  src/features/ProductCardsView/model/hooks.ts
  src/features/ProductCardsView/model/types.ts
  src/features/ProductCardsView/ui/ProductCardsView.tsx
  src/pages/catalog/ui/CatalogPage.tsx
  src/widgets/category-products-widget/index.ts
  src/widgets/category-products-widget/ui/CategoryProductsWidget.tsx
Labels: Approved, Merge conflicts, Feature, Environment

#158 Fix bad resolve
  src/features/ProductCardsView/api/products.ts
  src/features/ProductCardsView/model/hooks.ts
Labels: Approved, Bug fix

#157 Header Navigation
  src/App.test.tsx
  src/pages/catalog/ui/CatalogPage.tsx
  src/pages/login/ui/LoginPage.tsx
  src/pages/main/MainPage.tsx
  src/pages/notFound/ui/NotFoundPage.tsx
  src/pages/register/ui/RegisterPage.tsx
  src/shared/api/index.ts
  src/shared/api/tokens/helpers.ts
  src/shared/constants/paths.ts
  src/shared/ui/AuthLayout/index.ts
  src/shared/ui/AuthLayout/ui/AuthLayout.tsx
  src/shared/ui/AuthLayout/ui/style.ts
  src/shared/ui/Header/Header.tsx
  src/shared/ui/Header/index.ts
  src/shared/ui/Logo/Logo.tsx
  src/widgets/Footer/style.ts
  src/widgets/Header/index.ts
  src/widgets/Header/model/items.ts
  src/widgets/Header/ui/Header.tsx
  src/widgets/Header/ui/HeaderDrawer/HeaderDrawer.tsx
  src/widgets/Header/ui/HeaderDrawer/style.ts
  src/widgets/Header/ui/style.ts
  src/widgets/registration-form/ui/style.ts
Labels: Approved, Feature

#159 Categories navigation, breadcrumbs and fix some errors
  package-lock.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/app/routes/AppRoutes.tsx
  src/app/routes/Layout/Layout.tsx
  src/app/routes/Layout/index.ts
  src/app/routes/index.ts
  src/app/store.ts
  src/app/store/store.ts
  src/app/types.d.ts
  src/entities/category/api/categories.ts
  src/entities/category/index.ts
  src/entities/category/model/model.ts
  src/entities/category/model/slice.ts
  src/entities/category/ui/CategoryView.tsx
  src/entities/product-card/ui/style.ts
  src/entities/products-filter/ui/FilterContent/FilterBox/FilterCheckbox.tsx
  src/entities/products-filter/ui/FilterContent/FilterBox/FilterSectionBox.tsx
  src/entities/products-filter/ui/FilterContent/FilterContent.tsx
  src/entities/products-filter/ui/FilterContent/PriceFilterBox/PriceFilterBox.tsx
  src/entities/products-filter/ui/FilterContent/PriceSlider/PriceSlider.tsx
  src/entities/products-filter/ui/ProductsFilter.tsx
  src/entities/products-search/model/hooks.ts
  src/entities/products-search/ui/ProductsSearch.tsx
  src/entities/products-sort-select/ui/ProductsSortSelect.tsx
  src/entities/products-sort-select/ui/style.ts
  src/features/Breadcrumbs/index.ts
  src/features/Breadcrumbs/ui/Breadcrumbs.tsx
  src/features/ProductCardsView/api/products.ts
  src/features/ProductCardsView/model/hooks.ts
  src/features/ProductCardsView/model/types.ts
  src/features/ProductCardsView/ui/ProductCardsView.tsx
  src/features/ProductCardsView/ui/style.ts
  src/index.tsx
  src/pages/catalog/ui/CatalogPage.tsx
  src/pages/login/ui/LoginPage.tsx
  src/pages/main/MainPage.tsx
  src/pages/register/ui/RegisterPage.tsx
  src/shared/constants/paths.ts
  src/shared/ui/CustomButton/style.ts
  src/widgets/Header/model/items.ts
  src/widgets/Header/ui/Header.tsx
  src/widgets/Header/ui/HeaderDrawer/HeaderDrawer.tsx
  src/widgets/category-products-widget/ui/CategoryProductsWidget.tsx
Labels: Need review, Feature, Bug fix, Environment

#160 CustomSwiper component
  package-lock.json
  package.json
  src/shared/ui/CustomSwiper/CustomSwiper.tsx
  src/shared/ui/CustomSwiper/index.ts
  src/shared/ui/CustomSwiper/style.ts
  src/shared/ui/CustomSwiper/swiper-styles.css
Labels: Need review, Feature, Environment

#162 ProductImageSlider component
  src/entities/product-image-slider/index.ts
  src/entities/product-image-slider/ui/ProductImageSlider.tsx
  src/entities/product-image-slider/ui/style.ts
  src/shared/ui/CustomSwiper/CustomSwiper.tsx
  src/shared/ui/CustomSwiper/style.ts
Labels: Need review, Approved, Feature

#166 `PriceTag`
  src/shared/ui/PriceTag/PriceTag.tsx
  src/shared/ui/PriceTag/index.ts
  src/shared/ui/PriceTag/style.ts
Labels: Approved, Feature

#167 Profile page
  src/features/AboutForm/ui/AboutForm.tsx
  src/features/AddressCard/index.ts
  src/features/AddressCard/model/types.ts
  src/features/AddressCard/ui/AddressCard.tsx
  src/features/AddressCard/ui/style.ts
  src/features/AddressForm/ui/AddressForm.tsx
  src/features/AddressForm/ui/style.ts
  src/pages/profile/index.ts
  src/pages/profile/ui/ProfilePage.tsx
  src/pages/profile/ui/style.ts
  src/shared/api/apiRoot.ts
  src/shared/api/customers.ts
  src/shared/api/tokens/tokens.ts
  src/shared/constants/colors.ts
  src/shared/constants/paths.ts
  src/shared/types/Customer.ts
  src/shared/ui/AdressType/index.ts
  src/shared/ui/AdressType/ui/AdressTypeContainer.tsx
  src/shared/ui/AdressType/ui/AdressTypeItem.tsx
  src/shared/ui/AdressType/ui/style.ts
  src/shared/ui/CustomSwitch/CustomSwitch.tsx
  src/shared/ui/CustomTextField/CustomTextField.tsx
  src/shared/ui/addButton/AddButton.tsx
  src/widgets/bonuses-list/index.ts
  src/widgets/bonuses-list/ui/BonusesList.tsx
  src/widgets/bonuses-list/ui/style.ts
  src/widgets/profile-form/index.ts
  src/widgets/profile-form/ui/ProfileForm.tsx
  src/widgets/profile-form/ui/style.ts
  src/widgets/profile/CustomerAddressForm/model/schema.ts
  src/widgets/profile/CustomerAddressForm/model/types.ts
  src/widgets/profile/CustomerAddressForm/ui/CustomerAddressForm.tsx
  src/widgets/profile/CustomerAddressForm/ui/lib/hellpers.ts
  src/widgets/profile/CustomerAddressForm/ui/style.ts
  src/widgets/profile/CustomerInformationForm/ui/CustomerInformationForm.tsx
  src/widgets/profile/CustomerInformationForm/ui/style.ts
  src/widgets/profile/address-accordion/AddressAccordion.tsx
  src/widgets/profile/address-accordion/lib/helpers.ts
  src/widgets/profile/address-accordion/style.ts
  src/widgets/profile/index.ts
Labels: Approved, Feature

#168 Product page redirect
  src/app/routes/AppRoutes.tsx
  src/entities/product-card/ui/ProductCard.tsx
  src/features/ProductCardsView/ui/ProductCardsView.tsx
  src/pages/detailedProduct/DetailedProductPage.tsx
  src/pages/detailedProduct/index.ts
  src/shared/constants/paths.ts
  src/shared/ui/FavoriteButton/index.ts
  src/shared/ui/FavoriteButton/ui/FavoriteButton.tsx
  src/shared/ui/FavoriteButton/ui/style.ts
Labels: Approved, Feature

#163 `ProductPage`
  src/pages/detailedProduct/DetailedProductPage.tsx
  src/shared/ui/FavoriteButton/ui/style.ts
Labels: Approved, Feature

#170 Profile page redirect
  src/app/routes/AppRoutes.tsx
  src/pages/profile/ui/ProfilePage.tsx
  src/shared/constants/paths.ts
  src/widgets/Header/model/items.ts
Labels: Need review, Feature, Bug fix

#169 Personal info edit
  src/features/AboutForm/ui/AboutForm.tsx
  src/features/AddressCard/model/types.ts
  src/features/CustomerAboutForm/index.ts
  src/features/CustomerAboutForm/model/schema.ts
  src/features/CustomerAboutForm/model/types.ts
  src/features/CustomerAboutForm/ui/CustomerAboutForm.tsx
  src/pages/profile/ui/ProfilePage.tsx
  src/shared/api/customers.ts
  src/widgets/profile/CustomerInformationForm/model/schema.ts
  src/widgets/profile/CustomerInformationForm/model/types.ts
  src/widgets/profile/CustomerInformationForm/ui/CustomerInformationForm.tsx
  src/widgets/profile/CustomerInformationForm/ui/style.ts
  src/widgets/profile/address-accordion/AddressAccordion.tsx
  src/widgets/profile/address-accordion/lib/types.ts
  src/widgets/profile/index.ts
Labels: Need review, In progress, Feature

#171 Header redirect to Profile page and logout
  src/app/routes/Layout/Layout.tsx
  src/pages/catalog/ui/CatalogPage.tsx
  src/pages/login/ui/LoginPage.tsx
  src/pages/main/MainPage.tsx
  src/pages/profile/ui/ProfilePage.tsx
  src/pages/register/ui/RegisterPage.tsx
  src/widgets/Header/ui/Header.tsx
  src/widgets/Header/ui/HeaderDrawer/HeaderDrawer.tsx
  src/widgets/Header/ui/HeaderDrawer/ProfileMenu.tsx
Labels: Need review, Feature, Bug fix

#172 Customer password change
  src/features/ChangePasswordAccordion/api/change-password.ts
  src/features/ChangePasswordAccordion/index.ts
  src/features/ChangePasswordAccordion/ui/ChangePasswordAccordion.tsx
  src/pages/profile/ui/ProfilePage.tsx
  src/widgets/profile-form/index.ts
  src/widgets/profile-form/ui/ProfileForm.tsx
  src/widgets/profile-form/ui/style.ts
  src/widgets/profile/address-accordion/AddressAccordion.tsx
Labels: Need review, Feature

#173 fix: change icons
  public/favicon.svg
  public/index.html
  src/shared/ui/assets/icons/logo/logo_big.svg
  src/shared/ui/assets/icons/logo/logo_small.svg
  src/shared/ui/assets/icons/logo/logo_small_bg.svg
Labels: Approved, Feature

#175 Product page
  src/pages/detailedProduct/DetailedProductPage.tsx
  src/pages/detailedProduct/model/hooks.ts
  src/pages/detailedProduct/model/slice.ts
  src/pages/detailedProduct/style.ts
  src/shared/api/product.ts
  src/shared/types/product.ts
Labels: Approved, Feature

#176 Product route fix
  src/shared/api/product.ts
Labels: Need review, Bug fix

#199 Product page
  src/pages/detailedProduct/DetailedProductPage.tsx
Labels: Approved, Bug fix

#210 Order summary markup
  src/features/OrderSummary/index.ts
  src/features/OrderSummary/ui/OrderSummary.tsx
  src/features/OrderSummary/ui/OrderSummaryItem/OrderSummaryItem.tsx
  src/features/OrderSummary/ui/style.ts
Labels: Need review, Approved, Feature

#207 Cart item view markup
  src/features/CartItemView/index.ts
  src/features/CartItemView/ui/CartItemView.tsx
  src/features/CartItemView/ui/style.ts
  src/shared/ui/PriceTag/style.ts
Labels: Need review, Approved, Feature

#204 Catalog pagination
  src/features/ProductCardsView/api/products.ts
  src/features/ProductCardsView/lib/helpers.ts
  src/features/ProductCardsView/model/hooks.ts
  src/features/ProductCardsView/model/types.ts
  src/features/ProductCardsView/ui/ProductCardsView.tsx
Labels: Need review, Approved, Feature

#203 Add button markup "Add to card" in ProductCard component
  src/entities/product-card/ui/ProductCard.tsx
Labels: Need review, Approved, Feature

#201 Cart page route
  src/app/routes/AppRoutes.tsx
  src/pages/cart/index.ts
  src/pages/cart/ui/CartPage.tsx
  src/shared/constants/paths.ts
Labels: Need review, Approved, Feature

#213 Header basket badge
  src/widgets/Header/ui/Header.tsx
  src/widgets/Header/ui/HeaderCartButton/HeaderCartButton.tsx
  src/widgets/Header/ui/HeaderDrawer/HeaderDrawer.tsx
Labels: Need review, Feature

#205 Add product to Cart and show added items in Cart page
  src/app/store/store.ts
  src/entities/cart/api/cart.ts
  src/entities/cart/index.ts
  src/entities/cart/model/hooks.ts
  src/entities/cart/model/slice.ts
  src/pages/cart/ui/CartPage.tsx
  src/pages/detailedProduct/DetailedProductPage.tsx
  src/shared/api/apiRoot.ts
  src/shared/api/product.ts
  src/shared/api/tokens/tokens.ts
  src/widgets/Header/ui/HeaderDrawer/ProfileMenu.tsx
  src/widgets/cart-items-list/index.ts
  src/widgets/cart-items-list/lib/helpers.ts
  src/widgets/cart-items-list/model/hooks.ts
  src/widgets/cart-items-list/model/types.ts
  src/widgets/cart-items-list/ui/CartItemsList.tsx
Labels: Need review, Feature

#218 Cart Product change quantity
  src/entities/cart/api/cart.ts
  src/entities/cart/index.ts
  src/entities/cart/lib/helpers.ts
  src/entities/cart/model/slice.ts
  src/features/CartItemView/index.ts
  src/features/CartItemView/ui/CartItemView.tsx
  src/features/CartProductView/index.ts
  src/features/CartProductView/model/types.ts
  src/features/CartProductView/ui/CartProductView.tsx
  src/features/CartProductView/ui/style.ts
  src/pages/cart/ui/CartPage.tsx
  src/widgets/cart-items-list/index.ts
  src/widgets/cart-items-list/model/hooks.ts
  src/widgets/cart-items-list/ui/CartItemsList.tsx
  src/widgets/cart-products-list/index.ts
  src/widgets/cart-products-list/lib/helpers.ts
  src/widgets/cart-products-list/model/hooks.ts
  src/widgets/cart-products-list/ui/CartProductsList.tsx
Labels: Approved, Feature

#219 Cart clear button
  src/features/CartClearButton/index.ts
  src/features/CartClearButton/ui/CartClearButton.tsx
Labels: Approved, Feature

#214 Remove not found background
  src/pages/notFound/ui/NotFoundPage.tsx
  src/pages/notFound/ui/style.ts
Labels: Approved, Bug fix

#222 Cart Product remove
  src/entities/cart/api/cart.ts
  src/entities/cart/lib/helpers.ts
  src/entities/cart/model/hooks.ts
  src/entities/cart/model/slice.ts
  src/features/CartProductView/ui/CartProductView.tsx
  src/widgets/cart-products-list/lib/helpers.ts
  src/widgets/cart-products-list/model/hooks.ts
Labels: Approved, Feature

#223 Cart empty message
  src/widgets/cart-products-list/ui/CartProductsList.tsx
Labels: Approved, Feature

#225 Cart total cost and merge anonymous cart with user cart
  src/entities/cart/model/slice.ts
  src/features/ChangePasswordAccordion/api/change-password.ts
  src/features/OrderSummary/ui/OrderSummary.tsx
  src/pages/cart/ui/CartPage.tsx
  src/shared/api/customers.ts
  src/widgets/cart-products-list/model/hooks.ts
  src/widgets/login-form/ui/LoginForm.tsx
  src/widgets/registration-form/ui/RegistrationForm.tsx
Labels: Approved, Feature

#226 Cart discount code
  src/entities/cart/api/cart.ts
  src/entities/cart/model/hooks.ts
  src/features/DiscountCodeField/index.ts
  src/features/DiscountCodeField/ui/DiscountCodeField.tsx
  src/pages/cart/ui/CartPage.tsx
Labels: Approved, Feature

#227 Main page content
  src/pages/main/MainPage.tsx
  src/pages/main/index.ts
  src/pages/main/ui/MainPage.tsx
  src/pages/main/ui/style.ts
  src/shared/assets/images/index.ts
  src/shared/assets/images/main-bg.jpg
Labels: Approved, Feature

#231 Header badge counter and load cart data on start, login/logout and register
  src/app/routes/AppRoutes.tsx
  src/entities/cart/index.ts
  src/entities/cart/model/slice.ts
  src/widgets/Header/ui/HeaderCartButton/HeaderCartButton.tsx
  src/widgets/Header/ui/HeaderDrawer/ProfileMenu.tsx
  src/widgets/login-form/ui/LoginForm.tsx
  src/widgets/registration-form/ui/RegistrationForm.tsx
Labels: Approved, Feature

#233 Cart state fix
  src/entities/cart/lib/helpers.ts
  src/entities/cart/model/hooks.ts
  src/entities/cart/model/slice.ts
  src/entities/cart/model/types.ts
  src/features/CartProductView/ui/CartProductView.tsx
  src/features/OrderSummary/ui/OrderSummary.tsx
  src/pages/cart/ui/CartPage.tsx
  src/widgets/Header/ui/HeaderCartButton/HeaderCartButton.tsx
  src/widgets/cart-products-list/lib/helpers.ts
  src/widgets/cart-products-list/model/hooks.ts
  src/widgets/cart-products-list/ui/CartProductsList.tsx
Labels: Approved, Bug fix

#235 Fix adaptive layout
  src/entities/product-image-slider/ui/ProductImageSlider.tsx
  src/entities/product-image-slider/ui/style.ts
  src/features/CartProductView/ui/CartProductView.tsx
  src/features/CartProductView/ui/style.ts
  src/pages/detailedProduct/DetailedProductPage.tsx
Labels: Approved, Bug fix

#237 Fix cookies
  src/shared/api/tokens/helpers.ts
  src/shared/api/tokens/tokens.ts
Labels: Approved, Bug fix

#217 Detailed team description
  src/features/AboutUsItem/index.ts
  src/features/AboutUsItem/ui/AboutUsItem.tsx
  src/features/AboutUsItem/ui/style.ts
  src/pages/about/ui/AboutPage.tsx
  src/pages/about/ui/style.ts
  src/shared/assets/developers-bio/Jamal/JamalImage.jpg
  src/shared/assets/developers-bio/Jamal/bio.ts
  src/shared/assets/developers-bio/Rashid/bio.ts
  src/shared/assets/developers-bio/Rashid/man.png
  src/shared/assets/developers-bio/Roman/bio.ts
  src/shared/assets/developers-bio/Roman/man.png
  src/shared/assets/developers-bio/index.ts
Labels: Approved, Feature

#236 Cart clear button
  src/entities/cart/api/cart.ts
  src/entities/cart/model/hooks.ts
  src/features/CartClearButton/ui/CartClearButton.tsx
  src/pages/cart/ui/CartPage.tsx
Labels: Approved, Feature, Bug fix

#241 Detailed product page add/remove product button fix
  src/pages/detailedProduct/DetailedProductPage.tsx
Labels: Approved, Bug fix

#242 Pagination backend fix
  src/features/ProductCardsView/api/products.ts
  src/features/ProductCardsView/model/hooks.ts
  src/features/ProductCardsView/model/types.ts
  src/features/ProductCardsView/ui/ProductCardsView.tsx
Labels: Approved, Feature, Bug fix

#244 Discounc code list
  .eslintrc.js
  src/pages/main/ui/MainPage.tsx
  src/pages/main/ui/style.ts
  src/shared/api/discountCodes.ts
  src/shared/ui/DiscountCodeCard/index.ts
  src/shared/ui/DiscountCodeCard/ui/DiscountCodeCard.tsx
  src/shared/ui/DiscountCodeCard/ui/style.ts
  src/widgets/DiscountCodeList/index.ts
  src/widgets/DiscountCodeList/model/hooks.ts
  src/widgets/DiscountCodeList/ui/DiscountCodeList.tsx
  src/widgets/DiscountCodeList/ui/style.tsx
Labels: Approved, Feature

#245 Tests
  src/entities/cart/api/cart.test.ts
  src/entities/category/api/categories.test.ts
  src/features/AboutUsItem/ui/AboutUsItem.test.tsx
  src/features/AddressCard/ui/AddressCard.test.tsx
  src/features/CartClearButton/ui/CartClearButton.test.tsx
  src/features/CartProductView/ui/CartProductView.test.tsx
  src/features/DiscountCodeField/ui/DiscountCodeField.test.tsx
  src/features/ProductCardsView/ui/ProductCardsView.test.tsx
Labels: Approved, Feature

#247 feat: add description for promo codes condition
  src/features/DiscountCodeField/ui/DiscountCodeField.tsx
Labels: Approved, Feature

#248 fix: fix endless query loop
  src/widgets/DiscountCodeList/model/hooks.ts
Labels: Approved, Bug fix

#250 Fix `MainPage` adaptive
  src/pages/main/ui/style.ts
  src/shared/ui/DiscountCodeCard/ui/style.ts
Labels: Approved, Bug fix
