Repository duumbling/e-commerce-application, pull requests merged in 2023-08, with the labels that each got.

#1 Set up environment
  .eslintrc.js
  .gitignore
  .husky/pre-commit
  .prettierrc
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/app/hooks.ts
  src/app/store.ts
  src/index.css
  src/index.tsx
  src/logo.svg
  src/react-app-env.d.ts
  src/setupTests.ts
  tsconfig.json
Labels: Approved

#2 Update README
  README.md
Labels: Approved

#40 Button Component
  .husky/pre-commit
  src/shared/.gitkeep
  src/shared/constants/colors.ts
  src/shared/ui/CustomButton/CustomButton.tsx
  src/shared/ui/CustomButton/style.ts
Labels: Approved, Need changes

#44 Turn off return types
  .eslintrc.js
  src/App.tsx
  src/app/hooks.ts
Labels: Feature

#45 CommerceTools Typescript SDK
  package-lock.json
  package.json
  src/shared/api/apiRoot.ts
Labels: Approved

#77 Input component
  src/shared/constants/colors.ts
  src/shared/constants/sizes.ts
  src/shared/ui/CustomTextField/CustomTextField.tsx
  src/shared/ui/CustomTextField/style.ts
Labels: Need review

#78 Sprint 1
  src/shared/constants/colors.ts
  src/shared/constants/sizes.ts
  src/shared/ui/CustomTextField/CustomTextField.tsx
  src/shared/ui/CustomTextField/style.ts
Labels: Approved

#84 Fix TextField styles bug
  src/shared/ui/CustomTextField/CustomTextField.tsx
  src/shared/ui/CustomTextField/style.ts
Labels: Approved, Bug fix

#85 Optimize linting pattern
  .eslintrc.js
  tsconfig.json
Labels: Bug fix

#81 Routing
  .eslintrc.js
  package-lock.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/index.tsx
  src/pages/.gitkeep
  src/pages/login/LoginPage.tsx
  src/pages/login/index.ts
  src/pages/main/MainPage.tsx
  src/pages/main/index.ts
  src/pages/notFound/NotFoundPage.tsx
  src/pages/notFound/index.ts
  src/pages/register/RegisterPage.tsx
  src/pages/register/index.ts
  src/shared/constants/paths.ts
  src/shared/ui/Header/Header.tsx
  src/shared/ui/Header/index.ts
  src/shared/ui/Layout/Layout.tsx
  src/shared/ui/Layout/index.ts
Labels: Approved, Feature

#87 Address form feature
  src/features/.gitkeep
  src/features/AddressForm/index.ts
  src/features/AddressForm/ui/AddressForm.tsx
  src/features/AddressForm/ui/style.ts
  src/features/index.ts
  src/shared/ui/CustomButton/CustomButton.tsx
  src/shared/ui/CustomButton/index.ts
  src/shared/ui/CustomTextField/CustomTextField.tsx
  src/shared/ui/CustomTextField/index.ts
  src/shared/ui/CustomTextField/style.ts
Labels: Approved, Feature

#82 Switch component
  src/shared/constants/colors.ts
  src/shared/constants/sizes.ts
  src/shared/ui/CustomSwitch/CustomSwitch.tsx
  src/shared/ui/CustomSwitch/style.ts
Labels: Approved

#90 Header
  src/pages/login/LoginPage.tsx
  src/pages/main/MainPage.tsx
  src/pages/notFound/NotFoundPage.tsx
  src/pages/register/RegisterPage.tsx
  src/shared/ui/Header/Header.tsx
  src/shared/ui/Logo/Logo.tsx
  src/shared/ui/Logo/index.ts
Labels: Need review, Feature

#89 Registration form layout
  package-lock.json
  package.json
  src/features/AboutForm/index.ts
  src/features/AboutForm/ui/AboutForm.tsx
  src/features/AddressForm/ui/style.ts
  src/shared/constants/mediaQuery.ts
  src/shared/ui/CustomButton/style.ts
  src/shared/ui/CustomTextField/CustomTextField.tsx
  src/shared/ui/CustomTextField/style.ts
  src/shared/ui/PasswordField/PasswordField.tsx
  src/shared/ui/PasswordField/index.ts
  src/widgets/registration-form/index.ts
  src/widgets/registration-form/ui/RegistrationForm.tsx
  src/widgets/registration-form/ui/style.ts
Labels: Need review, Feature

#91 Login form layout
  src/widgets/login-form/index.ts
  src/widgets/login-form/ui/LoginForm.tsx
  src/widgets/login-form/ui/style.ts
Labels: Approved, In progress, Feature

#93 Registration form submit
  src/features/AboutForm/ui/AboutForm.tsx
  src/features/AddressForm/index.ts
  src/features/AddressForm/model/countries.ts
  src/features/AddressForm/model/types.ts
  src/features/AddressForm/ui/AddressForm.tsx
  src/features/AddressForm/ui/style.ts
  src/features/index.ts
  src/shared/api/apiRoot.ts
  src/shared/api/customers.ts
  src/shared/api/index.ts
  src/shared/lib/errors/index.ts
  src/shared/lib/errors/types.ts
  src/shared/ui/CustomSnackBar/index.ts
  src/shared/ui/CustomSnackBar/ui/CustomSnackBar.tsx
  src/shared/ui/CustomTextField/CustomTextField.tsx
  src/shared/ui/PasswordField/PasswordField.tsx
  src/widgets/.gitkeep
  src/widgets/registration-form/lib/helpers.ts
  src/widgets/registration-form/model/types.ts
  src/widgets/registration-form/ui/RegistrationForm.tsx
  src/widgets/registration-form/ui/style.ts
Labels: Approved, Feature, Environment

#97 Ignore `.env`
  .gitignore
Labels: Bug fix, Environment

#94 Theme
  src/App.tsx
  src/shared/constants/colors.ts
  src/shared/ui/themes/index.ts
  src/shared/ui/themes/mainTheme.ts
Labels: Approved, Feature

#99 Registration common address
  src/App.tsx
  src/app/.gitkeep
  src/app/store.ts
  src/app/types.d.ts
  src/features/AddressForm/index.ts
  src/features/AddressForm/lib/helper.ts
  src/features/AddressForm/model/countries.ts
  src/features/AddressForm/model/slice.ts
  src/features/AddressForm/model/types.ts
  src/features/AddressForm/ui/AddressForm.tsx
  src/react-app-env.d.ts
  src/shared/model/hooks.ts
  src/shared/ui/PasswordField/PasswordField.tsx
  src/widgets/registration-form/api/registration.ts
  src/widgets/registration-form/lib/helpers.ts
  src/widgets/registration-form/ui/RegistrationForm.tsx
  tsconfig.json
Labels: Approved, Feature

#102 404 page
  src/pages/notFound/NotFoundPage.tsx
  src/pages/notFound/index.ts
  src/pages/notFound/ui/NotFoundPage.tsx
  src/pages/notFound/ui/style.ts
  src/shared/constants/colors.ts
  src/shared/constants/sizes.ts
Labels: Need review, In progress, Feature

#103 Registration redirect
  src/pages/register/RegisterPage.tsx
  src/shared/api/apiRoot.ts
  src/shared/api/customers.ts
  src/shared/constants/colors.ts
  src/shared/ui/CustomButton/style.ts
  src/widgets/registration-form/api/registration.ts
  src/widgets/registration-form/ui/RegistrationForm.tsx
Labels: Approved, Feature

#130 Login authorization
  src/pages/login/ui/LoginPage.tsx
  src/shared/api/apiRoot.ts
  src/shared/api/customers.ts
  src/shared/lib/errors/index.ts
  src/shared/lib/errors/types.ts
  src/widgets/login-form/lib/helpers.ts
  src/widgets/login-form/model/types.ts
  src/widgets/login-form/ui/LoginForm.tsx
  src/widgets/registration-form/lib/helpers.ts
Labels: Approved, Feature

#129 Change props types
  src/shared/ui/CustomSwitch/CustomSwitch.tsx
Labels: Approved, Feature

#132 Add background image
  src/pages/notFound/ui/NotFoundPage.tsx
  src/pages/notFound/ui/style.ts
  src/shared/assets/images/girl_1240.png
Labels: Approved, Feature

#133 Registration autologin
  src/features/AddressForm/ui/AddressForm.tsx
  src/features/AddressForm/ui/style.ts
  src/shared/api/customers.ts
  src/shared/api/index.ts
  src/shared/lib/validation/registration.ts
  src/shared/ui/CustomSwitch/CustomSwitch.tsx
  src/widgets/registration-form/ui/RegistrationForm.tsx
  src/widgets/registration-form/ui/style.ts
Labels: Need review, Feature, Bug fix

#136 Save token
  src/pages/login/ui/LoginPage.tsx
  src/pages/register/RegisterPage.tsx
  src/shared/api/apiRoot.ts
  src/shared/api/index.ts
  src/shared/api/tokens/helpers.ts
  src/shared/api/tokens/tokens.ts
Labels: Need review, Need changes, Feature

#139 feat: create _redirects file for netlify deploy
  public/_redirects
Labels: Need review, In progress, Feature

#142 Logo
  public/favicon.ico
  public/favicon.svg
  public/index.html
  src/shared/ui/Header/Header.tsx
  src/shared/ui/Logo/Logo.tsx
  src/shared/ui/assets/icons/logo/index.ts
  src/shared/ui/assets/icons/logo/logo_big.svg
  src/shared/ui/assets/icons/logo/logo_small.svg
  src/shared/ui/assets/icons/logo/logo_small_bg.svg
Labels: Need review, Feature

#141 Main page content for Sprint 2 Crosscheck
  src/App.test.tsx
  src/pages/main/MainPage.tsx
Labels: Need review, Feature

#140 Add Product Card
  src/entities/.gitkeep
  src/entities/product-card/index.ts
  src/entities/product-card/ui/ProductCard.tsx
  src/entities/product-card/ui/style.ts
  src/shared/constants/colors.ts
Labels: Approved, Feature

#146 Token save
  src/pages/login/ui/LoginPage.tsx
  src/pages/register/ui/RegisterPage.tsx
  src/shared/api/tokens/tokens.ts
Labels: Need review, Feature, Bug fix

#149 Validation fix
  package-lock.json
  package.json
  src/shared/lib/validation/index.ts
  src/shared/lib/validation/login.ts
  src/shared/lib/validation/validation.ts
  src/widgets/login-form/model/schema.ts
  src/widgets/login-form/ui/LoginForm.tsx
Labels: Approved, Bug fix, Environment

#148 Product card update layout
  src/entities/product-card/ui/ProductCard.tsx
  src/entities/product-card/ui/style.ts
  src/shared/constants/colors.ts
Labels: Approved, Feature

#144 ProductsView component
  src/entities/product-card/ui/ProductCard.tsx
  src/entities/product-card/ui/style.ts
  src/features/ProductCardsView/api/products.ts
  src/features/ProductCardsView/index.ts
  src/features/ProductCardsView/model/sort-options.ts
  src/features/ProductCardsView/model/types.ts
  src/features/ProductCardsView/ui/ProductsView.tsx
  src/features/ProductCardsView/ui/style.ts
Labels: Approved, Feature

#150 Products Sort and add Catalog page
  src/App.tsx
  src/app/store.ts
  src/entities/products-sort-select/index.ts
  src/entities/products-sort-select/model/select-items.ts
  src/entities/products-sort-select/model/slice.ts
  src/entities/products-sort-select/model/types.ts
  src/entities/products-sort-select/ui/ProductsSortSelect.tsx
  src/entities/products-sort-select/ui/style.ts
  src/features/ProductCardsView/api/products.ts
  src/features/ProductCardsView/model/sort-options.ts
  src/features/ProductCardsView/model/types.ts
  src/features/ProductCardsView/ui/ProductsView.tsx
  src/pages/catalog/index.ts
  src/pages/catalog/ui/CatalogPage.tsx
  src/shared/constants/paths.ts
Labels: Need review, Feature

#151 `Footer`
  src/shared/lib/helpers/styles/index.ts
  src/shared/lib/helpers/styles/styles.ts
  src/shared/ui/CustomButton/CustomButton.tsx
  src/shared/ui/CustomButton/index.ts
  src/shared/ui/Layout/Layout.tsx
  src/shared/ui/Link/Link.tsx
  src/shared/ui/SocialButton/SocialButton.tsx
  src/shared/ui/SocialButton/index.ts
  src/shared/ui/SocialButton/style.ts
  src/shared/ui/assets/icons/index.ts
  src/shared/ui/assets/icons/payment/index.ts
  src/shared/ui/assets/icons/payment/maestro_icon.png
  src/shared/ui/assets/icons/payment/paypal_icon.png
  src/shared/ui/assets/icons/payment/visa_icon.png
  src/shared/ui/assets/icons/social/facebook_icon.png
  src/shared/ui/assets/icons/social/index.ts
  src/shared/ui/assets/icons/social/signal_icon.png
  src/shared/ui/assets/icons/social/skype_icon.png
  src/shared/ui/assets/icons/social/telegram_icon.png
  src/shared/ui/assets/icons/social/viber_icon.png
  src/shared/ui/assets/icons/social/vk_icon.png
  src/widgets/Footer/Footer.tsx
  src/widgets/Footer/index.ts
  src/widgets/Footer/style.ts
Labels: Need review, Feature

#153 Sprint 2
  package-lock.json
  package.json
  src/shared/lib/helpers/styles/index.ts
  src/shared/lib/helpers/styles/styles.ts
  src/shared/lib/validation/index.ts
  src/shared/lib/validation/login.ts
  src/shared/lib/validation/validation.ts
  src/shared/ui/CustomButton/CustomButton.tsx
  src/shared/ui/CustomButton/index.ts
  src/shared/ui/Layout/Layout.tsx
  src/shared/ui/Link/Link.tsx
  src/shared/ui/SocialButton/SocialButton.tsx
  src/shared/ui/SocialButton/index.ts
  src/shared/ui/SocialButton/style.ts
  src/shared/ui/assets/icons/index.ts
  src/shared/ui/assets/icons/payment/index.ts
  src/shared/ui/assets/icons/payment/maestro_icon.png
  src/shared/ui/assets/icons/payment/paypal_icon.png
  src/shared/ui/assets/icons/payment/visa_icon.png
  src/shared/ui/assets/icons/social/facebook_icon.png
  src/shared/ui/assets/icons/social/index.ts
  src/shared/ui/assets/icons/social/signal_icon.png
  src/shared/ui/assets/icons/social/skype_icon.png
  src/shared/ui/assets/icons/social/telegram_icon.png
  src/shared/ui/assets/icons/social/viber_icon.png
  src/shared/ui/assets/icons/social/vk_icon.png
  src/widgets/Footer/Footer.tsx
  src/widgets/Footer/index.ts
  src/widgets/Footer/style.ts
  src/widgets/login-form/model/schema.ts
  src/widgets/login-form/ui/LoginForm.tsx
Labels: Approved, Feature

#152 Products Filter
  src/app/store.ts
  src/entities/product-card/ui/ProductCard.tsx
  src/entities/product-card/ui/style.ts
  src/entities/products-filter/index.ts
  src/entities/products-filter/lib/helpers.ts
  src/entities/products-filter/model/slice.ts
  src/entities/products-filter/model/types.ts
  src/entities/products-filter/ui/FilterContent/FilterBox/FilterCheckbox.tsx
  src/entities/products-filter/ui/FilterContent/FilterBox/FilterSectionBox.tsx
  src/entities/products-filter/ui/FilterContent/FilterContent.tsx
  src/entities/products-filter/ui/FilterContent/PriceSlider/PriceSlider.tsx
  src/entities/products-filter/ui/ProductsFilter.tsx
  src/entities/products-sort-select/index.ts
  src/entities/products-sort-select/model/select-items.ts
  src/entities/products-sort-select/model/slice.ts
  src/entities/products-sort-select/model/types.ts
  src/entities/products-sort-select/ui/ProductsSortSelect.tsx
  src/features/ProductCardsView/api/products.ts
  src/features/ProductCardsView/index.ts
  src/features/ProductCardsView/lib/helpers.ts
  src/features/ProductCardsView/model/hooks.ts
  src/features/ProductCardsView/model/types.ts
  src/features/ProductCardsView/ui/ProductCardsView.tsx
  src/features/ProductCardsView/ui/ProductsView.tsx
  src/features/ProductCardsView/ui/style.ts
  src/pages/catalog/ui/CatalogPage.tsx
  src/shared/model/hooks.ts
  src/shared/ui/Checkbox/Checkbox.tsx
  src/shared/ui/Checkbox/index.ts
Labels: Need review, Feature
